config/routes.rb
Rails.application.routes.draw do
  
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :users, only: :show # creates user_root_path
  resources :lessons, only: [:show, :index]
  resources :categories, only: [:show, :index]
  resources :lesson_steps, only: [:show, :index]
  resources :charges, only: [:new, :create]
  root 'welcome#index'

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :category
  has_many :lesson_steps
  has_many :purchases

  accepts_nested_attributes_for :category

  def steps
    lesson_steps.where(lesson_id: self.id)
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def show
    @lesson = Lesson.find(params[:id])
    @lesson_steps = @lesson.steps
    @user = current_user
    @stripe_btn_data = {
        key: "#{ Rails.configuration.stripe[:publishable_key] }",
        #key: "pk_test_z3971ulOJS1heFJXHUYprE5Z",
        description: "Lesson Land - #{@lesson.name}",
        amount: (@lesson.price*100).round, #Amount.default
        label: "Purchase for #{ActiveSupport::NumberHelper.number_to_currency(@lesson.price)}"
      }
  end

  def index
    @lessons = Lesson.all
  end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/index.html.erb
<div class="row">
      <div class="col-md-3">
        <h4>Lesson name</h4>
      </div>
      <div class="col-md-3">
        <h4>Description</h4>
      </div>
</div>

<% @lessons.each do |lesson| %>
  <div class="row">
  	<div class="col-md-3">
      <strong><%= link_to lesson.name, lesson_path(lesson) %></strong>
    </div>
    <div class="col-md-3">
      <p><%= lesson.description %></p>
    </div>
  </div>
<% end %>

app/views/lessons/show.html.erb
<div class="row">
	<div class="col-md-6">
		<h2><%= @lesson.name %></h2>
		<p><%= @lesson.description %> </p>
	</div>
<% unless @user.purchases.exists? lesson_id: @lesson.id %>
	<div class="col-md-1">
	  <%= stripe_charge_button(@lesson) %>
	</div>
<% end %>
</div>
<% if @user.purchases.exists? lesson_id: @lesson.id %>
	<%= render partial: 'lesson_steps/lesson_steps' %>
<% else %>
	<div class="row lesson-step">
		<div class="col-md-8">
			<%= image_tag("lesson_preview.png", alt: "lesson preview", class: "preview-lesson") %>
		</div>
	</div>
<% end %>	
	