config/routes.rb
Rails.application.routes.draw do
  
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :users, only: :show # creates user_root_path
  resources :lessons, only: [:show, :index]
  resources :categories, only: [:show, :index]
  resources :lesson_steps, only: [:show, :index]
  resources :charges, only: [:new, :create]
  root 'welcome#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :lessons
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :category
  has_many :lesson_steps
  has_many :purchases

  accepts_nested_attributes_for :category

  def steps
    lesson_steps.where(lesson_id: self.id)
  end
end

app/models/lesson_step.rb
class LessonStep < ActiveRecord::Base
  mount_uploader :photo, StepPhotoUploader

  belongs_to :lesson
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  belongs_to :user
  belongs_to :lesson
end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :profile_photo, AvatarUploader

  has_many :purchases
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: true
  validates :username, uniqueness: true, if: -> { self.username.present? }
end

app/controllers/Users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/Users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :profile_photo, :description, :superadmin])

  end

  def authenticate_admin_user!
      redirect_to '/' and return if user_signed_in? && !current_user.superadmin? 
      authenticate_user! 
    end 
    def current_admin_user #use predefined method name
      return nil if user_signed_in? && !current_user.superadmin? 
      current_user 
    end 
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
    if user_signed_in?
      @lesson = Lesson.find(params[:lesson_id])
      @stripe_btn_data = {
        key: "#{ Rails.configuration.stripe[:publishable_key] }",
        #key: "pk_test_z3971ulOJS1heFJXHUYprE5Z",
        description: "Lesson Land - #{@lesson.name}",
        amount: (@lesson.price*100).round, #Amount.default
        label: "Purchase for #{ActiveSupport::NumberHelper.number_to_currency(@lesson.price)}"
      }
    else
      redirect_to root_path
      flash[:notice] = "You must be signed in to do that."
    end
  end

  def create
    @lesson = Lesson.find(params[:lesson_id])

    @amount = @lesson.price
    @final_amount = @amount

    @code = params[:couponCode]

    if !@code.blank?
      @discount = get_discount(@code)

      if @discount.nil?
        flash[:error] = 'Coupon code is not valid or expired.'
        redirect_to new_charge_path
        return
      else
        @discount_amount = @discount 
        @final_amount = @amount - @discount_amount.to_f
      end

      charge_metadata = {
        :coupon_code => @code,
        :coupon_discount => (@discount * 100).to_s + '%'
      }
    end
       

    charge_metadata ||= {}

    # Creates a Stripe Customer object, for associating
    # with the charge

    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    

    # Where the real magic happens
    charge = Stripe::Charge.create(
      customer: customer.id, # Note -- this is NOT the user_id in your app
      amount: (@final_amount*100).round,
      description: "Lesson Land - #{@lesson.name}",
      currency: 'usd'
    )

    Purchase.create(lesson_id: @lesson.id, user_id: current_user.id, amount: @final_amount.round(2))

    flash[:notice] = "Thanks for purchasing #{@lesson.name}."
    redirect_to user_path(current_user) # or wherever

    # Stripe will send back CardErrors, with friendly messages
    # when something goes wrong.
    # This `rescue block` catches and displays those errors.
  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to new_charge_path
  end

  private

  COUPONS = {
    'FIRST' => 1.00,
    'SECOND' => 0.50
  }

  def get_discount(code)
    # Normalize user input
    code = code.gsub(/ +/, '')
    code = code.upcase
    COUPONS[code]
  end
end

app/controllers/lesson_steps_controller.rb
class LessonStepsController < ApplicationController
  def show
    @lesson_step = LessonStep.find(params[:id])
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def show
    @lesson = Lesson.find(params[:id])
    @lesson_steps = @lesson.steps
    @user = current_user
    @stripe_btn_data = {
        key: "#{ Rails.configuration.stripe[:publishable_key] }",
        #key: "pk_test_z3971ulOJS1heFJXHUYprE5Z",
        description: "Lesson Land - #{@lesson.name}",
        amount: (@lesson.price*100).round, #Amount.default
        label: "Purchase for #{ActiveSupport::NumberHelper.number_to_currency(@lesson.price)}"
      }
  end

  def index
    @lessons = Lesson.all
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController

  def index
    @purchases = Purchase.all

  end

  def new
    @purchase = Purchase.new
  end

  def create
    @purchase = purchases.build(purchase_params)

    if @purchase.save
    else
      flash.now[:alert] = "Error creating purchase. Please try again."
    end
  end

  def show
    @purchase = Purchase.find(params[:id])
  end

  private

  def purchase_params
    params.require(:purchase).permit(:lesson_id, :user_id, :amount)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lesson_steps_helper.rb
module LessonStepsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/stripe_helper.rb
module StripeHelper

  def stripe_charge_button(lesson)
    form_tag(charges_path, method: :create) +
      text_field_tag(:couponCode, nil, placeholder: 'enter coupon code', class: "coupon") +
      hidden_field_tag(:lesson_id, lesson.id) +
      javascript_include_tag("https://checkout.stripe.com/checkout.js", class: 'stripe-button', data: {key: @stripe_btn_data[:key], amount:  @stripe_btn_data[:amount], description: @stripe_btn_data[:description], label: @stripe_btn_data[:label] }) 
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lesson Land</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Lesson Land</a>
      </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to "Lessons", lessons_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
              <li><%= link_to 'Profile', user_path(current_user), :class => 'navbar-link navbar-right' %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link navbar-right'  %></li>
              
              <% else %>
              <li><%= link_to "Sign In", new_user_session_path, :class => 'navbar-link navbar-right'  %></li>
              <li><%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link navbar-right'  %></li>
              <% end %>
          </ul>
          <% if user_signed_in? %>
            <p class="navbar-text navbar-right">Signed in as: <strong><%= current_user.email %></strong></p>
          <% end %>  
          
        </div>
      </div>
    </nav>
    
    <div class="flash">
      <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
      <% elsif flash.now[:alert] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash.now[:alert] %>
      </div>
      <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
      <% end %>
    </div>
    <div class="container">
      <%= yield %>
    </div>

</body>
</html>